import ProductGrid from '../ProductGrid'
import coat from '@assets/generated_images/Black_cashmere_wool_coat_bdc7199b.png'
import blouse from '@assets/generated_images/Beige_silk_blouse_aba3fb75.png'
import trousers from '@assets/generated_images/Navy_tailored_trousers_2971ff9f.png'
import bag from '@assets/generated_images/White_leather_handbag_a51b7fc1.png'
import sweater from '@assets/generated_images/Cream_knit_sweater_ea49eca8.png'
import boots from '@assets/generated_images/Black_leather_ankle_boots_5c2dfe3d.png'
import blazer from '@assets/generated_images/Grey_wool_blazer_cbc57447.png'

export default function ProductGridExample() {
  const products = [
    {
      id: '1',
      slug: 'cashmere-wool-coat',
      name: 'Cashmere Wool Coat',
      sku: 'ATELIER-CWC-001',
      description: 'Luxurious cashmere wool coat',
      category_id: null,
      brand: 'ATELIER',
      size: null,
      colour: 'Black',
      fabric_quality: 'Premium Cashmere',
      premium_segment: true,
      wash_care: 'Dry clean only',
      imported_from: 'Italy',
      cost_price: '450.00',
      price: '890.00',
      sale_price: '670.00',
      is_on_sale: true,
      stock_quantity: 10,
      low_stock_threshold: 5,
      images: [coat],
      status: 'active',
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: '2',
      slug: 'silk-blouse',
      name: 'Silk Blouse',
      sku: 'MAISON-SB-002',
      description: 'Elegant silk blouse',
      category_id: null,
      brand: 'MAISON',
      size: null,
      colour: 'Beige',
      fabric_quality: 'Pure Silk',
      premium_segment: false,
      wash_care: 'Hand wash',
      imported_from: 'France',
      cost_price: '200.00',
      price: '420.00',
      sale_price: null,
      is_on_sale: false,
      stock_quantity: 15,
      low_stock_threshold: 3,
      images: [blouse],
      status: 'active',
      created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000), // 5 days ago
      updated_at: new Date()
    },
    {
      id: '3',
      slug: 'tailored-trousers',
      name: 'Tailored Trousers',
      sku: 'ATELIER-TT-003',
      description: 'Classic tailored trousers',
      category_id: null,
      brand: 'ATELIER',
      size: null,
      colour: 'Navy',
      fabric_quality: 'Wool Blend',
      premium_segment: false,
      wash_care: 'Dry clean',
      imported_from: 'Italy',
      cost_price: '150.00',
      price: '350.00',
      sale_price: null,
      is_on_sale: false,
      stock_quantity: 20,
      low_stock_threshold: 5,
      images: [trousers],
      status: 'active',
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: '4',
      slug: 'leather-handbag',
      name: 'Leather Handbag',
      sku: 'MAISON-LH-004',
      description: 'Premium leather handbag',
      category_id: null,
      brand: 'MAISON',
      size: null,
      colour: 'White',
      fabric_quality: 'Genuine Leather',
      premium_segment: true,
      wash_care: 'Wipe clean',
      imported_from: 'Italy',
      cost_price: '600.00',
      price: '1200.00',
      sale_price: null,
      is_on_sale: false,
      stock_quantity: 8,
      low_stock_threshold: 2,
      images: [bag],
      status: 'active',
      created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000), // 3 days ago
      updated_at: new Date()
    },
    {
      id: '5',
      slug: 'knit-sweater',
      name: 'Knit Sweater',
      sku: 'ATELIER-KS-005',
      description: 'Comfortable knit sweater',
      category_id: null,
      brand: 'ATELIER',
      size: null,
      colour: 'Cream',
      fabric_quality: 'Merino Wool',
      premium_segment: false,
      wash_care: 'Machine wash cold',
      imported_from: 'Portugal',
      cost_price: '120.00',
      price: '280.00',
      sale_price: null,
      is_on_sale: false,
      stock_quantity: 25,
      low_stock_threshold: 5,
      images: [sweater],
      status: 'active',
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: '6',
      slug: 'leather-ankle-boots',
      name: 'Leather Ankle Boots',
      sku: 'MAISON-LAB-006',
      description: 'Stylish leather ankle boots',
      category_id: null,
      brand: 'MAISON',
      size: null,
      colour: 'Black',
      fabric_quality: 'Genuine Leather',
      premium_segment: false,
      wash_care: 'Wipe clean',
      imported_from: 'Spain',
      cost_price: '250.00',
      price: '550.00',
      sale_price: '385.00',
      is_on_sale: true,
      stock_quantity: 12,
      low_stock_threshold: 3,
      images: [boots],
      status: 'active',
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: '7',
      slug: 'wool-blazer',
      name: 'Wool Blazer',
      sku: 'ATELIER-WB-007',
      description: 'Classic wool blazer',
      category_id: null,
      brand: 'ATELIER',
      size: null,
      colour: 'Grey',
      fabric_quality: 'Pure Wool',
      premium_segment: true,
      wash_care: 'Dry clean',
      imported_from: 'Italy',
      cost_price: '350.00',
      price: '780.00',
      sale_price: null,
      is_on_sale: false,
      stock_quantity: 6,
      low_stock_threshold: 2,
      images: [blazer],
      status: 'active',
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: '8',
      slug: 'cashmere-coat',
      name: 'Cashmere Coat',
      sku: 'MAISON-CC-008',
      description: 'Luxurious cashmere coat',
      category_id: null,
      brand: 'MAISON',
      size: null,
      colour: 'Black',
      fabric_quality: 'Premium Cashmere',
      premium_segment: true,
      wash_care: 'Dry clean only',
      imported_from: 'Italy',
      cost_price: '500.00',
      price: '950.00',
      sale_price: null,
      is_on_sale: false,
      stock_quantity: 4,
      low_stock_threshold: 1,
      images: [coat],
      status: 'active',
      created_at: new Date(),
      updated_at: new Date()
    }
  ]

  return <ProductGrid products={products} title="New Arrivals" />
}
